In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv("EdX.csv")
data.head(5)

,Name,University,Difficulty Level,Link,About,Course Description
0,How to Learn Online,edX,Beginner,https://www.edx.org/course/how-to-learn-online,Learn essential strategies for successful onli...,"Designed for those who are new to elearning, t..."
1,Programming for Everybody (Getting Started wit...,The University of Michigan,Beginner,https://www.edx.org/course/programming-for-eve...,"This course is a ""no prerequisite"" introductio...",This course aims to teach everyone the basics ...
2,CS50's Introduction to Computer Science,Harvard University,Beginner,https://www.edx.org/course/cs50s-introduction-...,An introduction to the intellectual enterprise...,"This is CS50x , Harvard University's introduct..."
3,The Analytics Edge,Massachusetts Institute of Technology,Intermediate,https://www.edx.org/course/the-analytics-edge,"Through inspiring examples and stories, discov...","In the last decade, the amount of data availab..."
4,Marketing Analytics: Marketing Measurement Str...,"University of California, Berkeley",Beginner,https://www.edx.org/course/marketing-analytics...,This course is part of a MicroMasters® Program,Begin your journey in a new career in marketin...

In [ ]:
data = data[['Name','University','Difficulty Level','Course Description']]

In [ ]:
data.head(5)

,Name,University,Difficulty Level,Course Description
0,How to Learn Online,edX,Beginner,"Designed for those who are new to elearning, t..."
1,Programming for Everybody (Getting Started wit...,The University of Michigan,Beginner,This course aims to teach everyone the basics ...
2,CS50's Introduction to Computer Science,Harvard University,Beginner,"This is CS50x , Harvard University's introduct..."
3,The Analytics Edge,Massachusetts Institute of Technology,Intermediate,"In the last decade, the amount of data availab..."
4,Marketing Analytics: Marketing Measurement Str...,"University of California, Berkeley",Beginner,Begin your journey in a new career in marketin...

In [ ]:
data['Name'] = data['Name'].str.replace(' ',',')
data['Name'] = data['Name'].str.replace(',,',',')
data['Name'] = data['Name'].str.replace(':','')
data['Course Description'] = data['Course Description'].str.replace(' ',',')
data['Course Description'] = data['Course Description'].str.replace(',,',',')
data['Course Description'] = data['Course Description'].str.replace('_','')
data['Course Description'] = data['Course Description'].str.replace(':','')
data['Course Description'] = data['Course Description'].str.replace('(','')
data['Course Description'] = data['Course Description'].str.replace(')','')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  if __name__ == '__main__':

In [ ]:
data.head(5)

,Name,University,Difficulty Level,Course Description
0,"How,to,Learn,Online",edX,Beginner,"Designed,for,those,who,are,new,to,elearning,th..."
1,"Programming,for,Everybody,(Getting,Started,wit...",The University of Michigan,Beginner,"This,course,aims,to,teach,everyone,the,basics,..."
2,"CS50's,Introduction,to,Computer,Science",Harvard University,Beginner,"This,is,CS50x,,Harvard,University's,introducti..."
3,"The,Analytics,Edge",Massachusetts Institute of Technology,Intermediate,"In,the,last,decade,the,amount,of,data,availabl..."
4,"Marketing,Analytics,Marketing,Measurement,Stra...","University of California, Berkeley",Beginner,"Begin,your,journey,in,a,new,career,in,marketin..."

In [ ]:
data['tags'] = data['Name'] + data['University'] + data['Difficulty Level'] + data['Course Description']

In [ ]:
data.head(5)

,Name,University,Difficulty Level,Course Description,tags
0,"How,to,Learn,Online",edX,Beginner,"Designed,for,those,who,are,new,to,elearning,th...","How,to,Learn,OnlineedXBeginnerDesigned,for,tho..."
1,"Programming,for,Everybody,(Getting,Started,wit...",The University of Michigan,Beginner,"This,course,aims,to,teach,everyone,the,basics,...","Programming,for,Everybody,(Getting,Started,wit..."
2,"CS50's,Introduction,to,Computer,Science",Harvard University,Beginner,"This,is,CS50x,,Harvard,University's,introducti...","CS50's,Introduction,to,Computer,ScienceHarvard..."
3,"The,Analytics,Edge",Massachusetts Institute of Technology,Intermediate,"In,the,last,decade,the,amount,of,data,availabl...","The,Analytics,EdgeMassachusetts Institute of T..."
4,"Marketing,Analytics,Marketing,Measurement,Stra...","University of California, Berkeley",Beginner,"Begin,your,journey,in,a,new,career,in,marketin...","Marketing,Analytics,Marketing,Measurement,Stra..."

In [ ]:
data['tags'].iloc[1]

'Programming,for,Everybody,(Getting,Started,with,Python)The University of MichiganBeginnerThis,course,aims,to,teach,everyone,the,basics,of,programming,computers,using,Python.,We,cover,the,basics,of,how,one,constructs,a,program,from,a,series,of,simple,instructions,in,Python.,The,course,has,no,pre-requisites,and,avoids,all,but,the,simplest,mathematics.,Anyone,with,moderate,computer,experience,should,be,able,to,master,the,materials,in,this,course.,This,course,will,cover,Chapters,1-5,of,the,textbook,"Python,for,Everybody".,Once,a,student,completes,this,course,they,will,be,ready,to,take,more,advanced,programming,courses.,This,course,covers,Python,3.,Computer,Science'

In [ ]:
new_df = data[['Name','tags']]
new_df.head(5)

,Name,tags
0,"How,to,Learn,Online","How,to,Learn,OnlineedXBeginnerDesigned,for,tho..."
1,"Programming,for,Everybody,(Getting,Started,wit...","Programming,for,Everybody,(Getting,Started,wit..."
2,"CS50's,Introduction,to,Computer,Science","CS50's,Introduction,to,Computer,ScienceHarvard..."
3,"The,Analytics,Edge","The,Analytics,EdgeMassachusetts Institute of T..."
4,"Marketing,Analytics,Marketing,Measurement,Stra...","Marketing,Analytics,Marketing,Measurement,Stra..."

In [ ]:
new_df['tags'] = data['tags'].str.replace(',',' ')
new_df['Name'] = data['Name'].str.replace(',',' ')
new_df.rename(columns = {'Name':'course_name'}, inplace = True)
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
new_df.head(5)

,course_name,tags
0,How to Learn Online,how to learn onlineedxbeginnerdesigned for tho...
1,Programming for Everybody (Getting Started wit...,programming for everybody (getting started wit...
2,CS50's Introduction to Computer Science,cs50's introduction to computer scienceharvard...
3,The Analytics Edge,the analytics edgemassachusetts institute of t...
4,Marketing Analytics Marketing Measurement Stra...,marketing analytics marketing measurement stra...

In [ ]:
new_df.shape

(720, 2)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
import nltk

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [ ]:
new_df['tags'] = new_df['tags'].apply(stem)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [ ]:
def result(course):
    course_index = new_df[new_df['course_name'] == course].index[0]
    distances = similarity[course_index]
    course_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6]
    p=0
    for i in course_list:
      if(p<6):
       print(new_df.iloc[i[0]].course_name)
       p+=1

In [ ]:
result('The Foundations of Happiness at Work')

Empathy and Emotional Intelligence at Work
Mindfulness and Resilience to Stress at Work
The Path to Happiness What Chinese Philosophy Teaches us about the Good Life
The Science of Happiness
edX101 Overview of Creating an edX Course

In [ ]:
import pickle